name: Repo Visualizer

on:
    push:
    workflow_dispatch:
    
jobs:
    repo-visualizer:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Update diagram
          id: make_diagram
          uses: githubocto/repo-visualizer@0.7.1
          with:
           output_file: "output-diagram.svg"
           should_push: false

        - name: Upload artifact
          uses: actions/upload-artifact@v4
          with:
           name: "diagram"
           path: "downloads"